### ISSUE TITLE
Implement gradle application plugin

### ISSUE THREAD

**Issue by ToddCostella** [WinterTechForum/skybar#1]
Implement application plugin to run the server and test client once the project structure is understood (by me)

**Comment by eirbjo** [comment]
Neat! We may also want to create a Maven build for the agent jar, we'll need to replace maven-shade-plugin with something in Gradle. (We need to create a "fat" jar including all classes, but also to relocate the classes to a different package space so they don't leak into the applications)

Perhaps something like this will work? https://github.com/johnrengelman/shadow

**Comment by marshallpierce** [comment]
We have the far jar with relocation; what remains to be done here?
