### ISSUE TITLE
Handle inner classes

### ISSUE THREAD

**Issue by marshallpierce** [WinterTechForum/skybar#9]
Perhaps sufficient application of getDeclaringClass() / looking for what classes have source available would do it.

**Comment by eirbjo** [comment]
I tested this by adding a PostHandler inner class to the MessageServlet class. Seems to me mapped fine  to the MessageServlet.java source file name just fine. Is this just working, or did you think about supporting inner classes at some other level?

**Comment by marshallpierce** [comment]
I hadn't tried it at all, but that's awesome that it works. :) Right now we're filtering classes with "$$" out; I'd like to make that more robust by seeing whether or not we can find the sources at instrumentation time so we can avoid the overhead if we can't usefully show it anyway.

**Comment by marshallpierce** [comment]
In what I have to assume was a moment of altitude-induced insanity, I didn't correctly follow the logic of how we get notified of visiting a source file and how that translates into the registry. So, I think this is a non-issue.
